CREATE DATABASE LojaPet;
GO
USE LojaPet;
GO
CREATE TABLE Estabelecimento (

IdEstabelecimento INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Endereco VARCHAR (300) NOT NULL,

);
GO
CREATE TABLE Veterinario(
IdVeterinario INT PRIMARY KEY IDENTITY NOT NULL,
CRV VARCHAR (30) NOT NULL,
Nome VARCHAR (100) NOT NULL,
IdEstabelecimento INT FOREIGN KEY REFERENCES Estabelecimento(IdEstabelecimento)
);
GO
CREATE TABLE Dono(
IdDono INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (100),
);
GO
CREATE TABLE TipoPet(
IdTipoPet INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR (100),
);
GO
CREATE TABLE Raca(
IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(100),
IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),
);
GO
CREATE TABLE Pet (
IdPet INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR (100),
DataNacimento DATETIME NOT NULL,
IdDono INT FOREIGN KEY REFERENCES Dono (IdDono),
IdRaca INT FOREIGN KEY REFERENCES Raca (IdRaca),
);

GO

CREATE TABLE Atendimento(
IdAtendimento INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR (100),
DataAtendimento DATETIME NOT NULL,
IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),



);









